### ISSUE TITLE
boot_device should be device

### ISSUE THREAD

**Issue by mathianasj** [oVirt/ovirt-engine-sdk-go#192]
## The problem

The name for boot_device in XMLBootDeviceWriteMany should be device for the tag name, not boot_device

## Environment

* Desktop OS/version
* Java version to run maven
* Go version under test
* The metamodel version speicifed in the root pom.xml
* The model version sepecified in the root pom.xml

## Description

[Description of the issue]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

## Link to logs [ Good To Have ]

Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs, and link them here.

**Comment by imjoey** [comment]
Hi @mathianasj , thank your for this issue. The tag name is auto generated by parsing ovirt-engine-api-model. Probably there's something wrong with the parsing rule. I'm working on this.
