### ISSUE TITLE
connection Test() doesn't really mean if a connection is authenticated and ready

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-engine-sdk-go#193]
## The problem

Seems like the Connection.Test() is broken. It doesn't really test if the connection is authenticated and can be used. 

For long running processes, which want to periodically invoke api commands, we want to use a cached connection. There is no need to recreate the connection over and over again, and to recreate sessions. 
On a case of a session termination, for any reason, we need to supply a way to clients the understand that, and create a new connection. Part of the problem is that ovirt doesn't support service-accounts which don't have a session nature. This itself deserve an RFE to ovirt separate issue)

For now I would like this to work reliably:

```go
response, err := connection.Test()
```

How to reproduce:
1. create a client code which creates a connection and wait for engine restart signal:
```go
package main

import (
        "fmt"
        "os"
        "time"
        "github.com/ovirt/go-ovirt"
)

func main() {
        c, err := ovirtsdk.NewConnectionBuilder().
                URL(url).
                Username(username).
                Password(password).
                CAFile(cafile).
                Insecure(insecure).
                Build()
        
        if err != nil {
                panic(err)
        }
        fmt.Printf("system service %v", c.SystemService().Get().MustSend())
        for {
                time.Sleep(5 * time.Second)
                f := "/tmp/engine.restart.done"
                fmt.Printf("waiting for egine restart - watchin file %s \n", f)
                fileInfo, err := os.Stat(f)
                if err != nil || fileInfo == nil {
                        fmt.Printf("file %s doesn't exists yet\n", f)
                        continue
                }
                break
        }

        fmt.Println(c.Test())
```
    
2. remove the session from the DB and restart ovirt-engine, to simulate session timeout
   to remove the session from the db , clear the session table:
   ```sql
       delete from engine_sessions;
   ```
3. now `touch /tmp/engine.restart.done`

**Expected behavior:** [What you expect to happen]
`Test()` should return `false` when the connection isn't authenticated

**Actual behavior:** [What actually happens]
`Test()` returns `nil` leading the client to think the connection is valid

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Comment by imjoey** [comment]
@rgolangh The idea of reusable connection and lightweight session is great to me. Looking forward to the RFE and I could also get involved in that job. 

Regarding to `Test()` for connection, my original purpose was to check if the attributes are able to correctly establish a connection. So `connection.Test()` will always try to redo the authentication if no existed `sshToken`, and lead to the issue mentioned  above. I like your opinion to make `Test()` more reliable. Many thanks to you for this.

**Comment by rgolangh** [comment]
Another thing that bothers me, is that when the session isn't authenticated, the sdk code returns an error to process an html, which is what the api returns when redirecting the connection if its not autheticated.

**Comment by rgolangh** [comment]
@imjoey this is kind of urgent to me - I can take it, and would just need a review from you.

**Comment by rgolangh** [comment]
here is a working prototype so far:
```
func (c *Connection) Test() error {
	options, err := http.NewRequest(http.MethodOptions, "", nil)
	if err != nil {
		// shouldn't fail to construct a request, but report anyway.
		return err
	}
	// a simple http OPTIONS request is the lightest method to test auth.
	_, err = c.client.Do(options)
	if err != nil {
		// failed, then clear state.
		c.ssoToken = ""
	}
	_, err = c.authenticate()
	return err
}
```

**Comment by imjoey** [comment]
> Another thing that bothers me, is that when the session isn't authenticated, the sdk code returns an error to process an html, which is what the api returns when redirecting the connection if its not autheticated.

Hi @rgolangh , Apologize for being late as no chunk of time to have a in-depth consideration about this. Hope not block your work.

Regarding the html error, shall we check the status code of the response in advance before calling `json.Unmarshal(body, &instance-of-ssoResponseJSON)`?

**Comment by rgolangh** [comment]
thanks for looking, yes that would probably be the way to go. 
I would expect an error code of 401 . In fact any > 300 should be not marshalled?
We don't have something to handle response code in the SDK?

**Comment by imjoey** [comment]
The response codes of the APIs sent to engine are handled, but not for the one of the APIs to access SSO. See the codes here at https://github.com/oVirt/ovirt-engine-sdk-go/blob/8e4607561f1a518a20bde242d18639984fee33aa/sdk/ovirtsdk/connection.go#L285-L290. I could fix this by return an error when response code > 300. What's your insights? Please let me know. Thanks.

**Comment by rgolangh** [comment]
Yes I think we should handle that for all codes which are >= 300

**Comment by imjoey** [comment]
That's right. 300 should be also included. Thanks for the correction.

**Comment by rgolangh** [comment]
You had a chance to review #197?

**Comment by imjoey** [comment]
> You had a chance to review #197?

**Comment by imjoey** [comment]
> You had a chance to review #197?

Yep, it's merged and thank you for that. Do you think a rapid new release is required for your current work?

**Comment by rgolangh** [comment]
Not urgemt - I would currently bump ovirt/cluster-api-provider go module to use that.
