### ISSUE TITLE
Missing interfaces

### ISSUE THREAD

**Issue by pkliczewski** [oVirt/ovirt-engine-sdk-go#199]
## The problem

In order to write tests to make sure that the sdk worked in the context of the code it was written in it is needed to create interfaces. This should be part of this repo.

## Environment

Please take a look [here](https://github.com/kubevirt/containerized-data-importer/pull/1042/files/d0b58ad167fe7833c61b28f5c53a8c2360b2b23d#diff-0e4c2577f78e99d674b98c3e3acba61dR318).

## Steps to Reproduce

1. Try to write tests for the code which uses this sdk and mock different responses.

**Comment by sandrobonazzola** [comment]
@pkliczewski did #1042 fix this issue? @imjoey ?

**Comment by janosdebugs** [comment]
Hey folks, as we pick old issues, no I do not believe that this issue has ever been fixed.

In the absence of a PR to resolve this issue at the root I would recommend taking a look at the [go-ovirt-client overlay](https://github.com/ovirt/go-ovirt-client), which attempts to provide a friendlier API to oVirt using this library as a backend, as well as a built-in mock facility. However, it only contains a partial implementation that is extended on an as-needed basis. (PRs are most welcome.)

**Comment by janosdebugs** [comment]
@pkliczewski I'm closing this issue as we agreed that it'd better to use go-ovirt-client for your purposes. Anyone else: feel free to reopen or file a new issue if this is still needed.
