### ISSUE TITLE
[VM initialization] - Please generate the SDK against 4.3.9-1 

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-engine-sdk-go#201]
## The problem

Initializing a VM in a generic way was a long standing issue of the API.
The variance between system requrired specific client interaction and caused fraction
in usage, and room for bugs:

To run a Centos VM and initialize it:
vm =  { .... initizliation: {...generic attributes and/or specific cloud init stuff} 
**vm.useCloudinit().run**

Window VM
vm = { .. initialization: { ... generic attributes and/or specific sysprep...}
**vm.useSysprep().run**

RHCOS/FCOS in 4.3.9-1 and above
vm = { ... osType=rhcos_x86 ... initialization: {...custom_script: ..} }

Now the API is streamlined, and relies on the os-type. so to initialize, just use:
**vm.useInitialization().run**

The only requirement is to make sure the right os is picked for the target VM. That's enough 
info to pick the right method.

* The metamodel version speicifed in the root pom.xml
latest metamode-4.3.9-1

**Expected behavior:** [What you expect to happen]
to run a vm and initializae in 4.3.9-1 and above inthe same way: vm.useInitialization().run

**Actual behavior:** [What actually happens]
Have to switch/case the VM type. Can't have a generic client.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% 

## Link to logs [ Good To Have ]
https://bugzilla.redhat.com/show_bug.cgi?id=1797659

This Change should follow a change in Terraform provider ovirt, to make it support all initialization
of all VMs. Currently is only supports cloud-init

**Comment by rgolangh** [comment]
@imjoey PTAL

**Comment by imjoey** [comment]
@rgolangh thanks for reporting and reminding. This is a very helpful feature. I'll working on this right now.

**Comment by rgolangh** [comment]
@imjoey I think we need branch per major version. I would like a 4.3 lease, along with 4.4. Do you
have any idea how to do that?

**Comment by imjoey** [comment]
@rgolangh yep,  good point. A new branch `sdk_4.3` is for 4.3.x release iteration.  While I'm a little confused about do we need the new branch `sdk_4.4` for 4.4.x versions, or simply use `master` branch? Any insights are welcome. Thanks.

**Comment by rgolangh** [comment]
master reflect 4.4 so I guess there is no other branch needed

**Comment by imjoey** [comment]
> master reflect 4.4 so I guess there is no other branch needed

Thanks @rgolangh  for your reply. I reviewed the previous releases and I'm afraid that I mistakenly matched the version of model and sdk. For example, the very early version `4.3.2` had already started using model `4.4.0`.

Do you have any good suggestions on how to handle this tough situation? Do we need to fix the previous mistake?

**Comment by rgolangh** [comment]
Calling @mwperina to participate.

To be clear we are talking on branches in this project and also in go-ovirt right?

For whoever is using the sdk's master branch, we keep tracking 4.4. 

For 4.3 lets create an `sdk_4.3` branch to be generated from `model_4.3` [branch ](https://github.com/oVirt/ovirt-engine-api-model/commits/model_4.3)

So if anyone is experienceing problem because they interfacing engine 4.3 with the current  version of the sdk (4.4) then they are advised to vendor the sdk_4.3 branch .

The semver of the tags on go-ovirt can then added on the branches. For example in sdk_4.3 branch we could tag v4.3.9.1 when we generate from it.

**Comment by imjoey** [comment]
@rgolangh yep, only this project needs multiple branches. Totally agreed with your insights above. One question I'm very concerned about is which commit would be the start point for this new `sdk_4.3` ?  

Cause the very early version 4.3.2 had already started using model 4.4.0, so I guess there may be two options:
1. Fork from tag `4.3.1` which was using model `4.3.21`
2. Fork from the latest release `4.4.1` (even `4.4.2` which includes the newest patch) and then simply change the model version to the latest `4.3.31`

From my point of view, I would prefer option 2.  What's your opinions? @rgolangh @mwperina Thanks.

**Comment by rgolangh** [comment]
On Fri, 13 Mar 2020 at 17:10, Joey <notifications@github.com> wrote:

> @rgolangh <https://github.com/rgolangh> yep, only this project needs
> multiple branches. Totally agreed with your insights above. One question
> I'm very concerned about is which commit would be the start point for this
> new sdk_4.3 ?
>
> Cause the very early version 4.3.2 had already started using model 4.4.0,
> so I guess there may be two options:
>
>    1. Fork from tag 4.3.1 which was using model 4.3.21
>    2. Fork from the latest release 4.4.1 (even 4.4.2 which includes the
>    newest patch) and then simply change the model version to the latest
>    4.3.31
>
> From my point of view, I would prefer option 2. What's your opinions?
> @rgolangh <https://github.com/rgolangh> @mwperina
> <https://github.com/mwperina> Thanks.
>
> —
>
Ok now I get more clearly what you are asking. Will the end result be
different for those 2 solutions?

**Comment by imjoey** [comment]
@rgolangh  I'm afraid yes. 

- Solution 1 will give us a more clean and correct commit history which only use model_4.3, but requires backporting plenty of patches from our latest version (sdk_4.4).
- Solution 2 does not need backporting patches, but will definitely contain the incorrect commit history, e.g.: sdk_4.3.9 uses model_4.4.10.

Neither would be perfect though.

**Comment by sandrobonazzola** [comment]
Is this still relevant? @rgolangh ? @imjoey ?

**Comment by rgolangh** [comment]
we are using effectively using go-ovirt 4.4 version which have compatibility with 4.3 engine. I still think this is important and we should have it, but not urgent.

**Comment by sandrobonazzola** [comment]
Closing due to capacity. We are using master everywhere so no real point in pushing for a 4.3 respin.
