### ISSUE TITLE
Adding VM to affinity group throws an XMLTagNotMatchError

### ISSUE THREAD

**Issue by jake2184** [oVirt/ovirt-engine-sdk-go#213]
## The problem

The SDK fails after (successfully) adding a VM to an affinity group. This may be an issue with the ovirt-engine API rather than the Go SDK.

## Environment

* Centos8, using the master branch of https://github.com/oVirt/go-ovirt
* oVirt Engine 4.4.1

## Description

I am adding a VM to an existing affinity group. The action is successful, but the return body of the XML is different to what the SDK expects so an error is thrown.

The documentation https://ovirt.github.io/ovirt-engine-api-model/master/#services/affinity_group_vms indicates that a Vm object is returned, and that is what the SDK is configured to expect. 

However, the engine returns an `action` object.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<action>
    <status>complete</status>
</action>
```

## Steps to Reproduce

1. Add a VM to an affinity group, using the affinity group vms service

**Expected behavior:**
The SDK to correctly handle the response from oVirt

**Actual behavior:** 
`Error: Tag not matched: expect <vm> but got <action>`
XML Tag error is throw

**Reproduces how often:**
Every time

## Link to logs
I am encountering this when extending a terraform provider, so the logs are a little obscure, and shouldn't really be needed.

The below gist has the simple code I am using to generate the error, and a curl command used to prove that the return from the API is not what the SDK expects. 
https://gist.github.com/jake2184/887eea9f25bcd69953bb70b5d08314fb

**Comment by janosdebugs** [comment]
Hey @jake2184 I'm sorry your issue has not been answered for so long. Could you check if this is still an issue?

**Comment by janosdebugs** [comment]
Hey @jake2184 I'm closing the issue for now, please feel free to reopen if this issue still pops up after the latest fixes.
