### ISSUE TITLE
Bump go-sdk api to latest version - model 4.4.18

### ISSUE THREAD

**Issue by liranr23** [oVirt/ovirt-engine-sdk-go#214]
## The problem

New api-model is available, we should upgrade the go-sdk to allow new features. Some will be needed later for terraform and OCP IPI.
https://gerrit.ovirt.org/#/c/111373/

**Comment by liranr23** [comment]
@imjoey looks like you did the versions bumps before. Are you still maintaining it?

**Comment by liranr23** [comment]
@emesika

**Comment by mwperina** [comment]
Most probably there will be api-model 4.4.19 next week, so please consider if it's worth to release this week
