### ISSUE TITLE
Supporting gollvm/llvm-goc

### ISSUE THREAD

**Issue by advancedwebdeveloper** [oVirt/ovirt-engine-sdk-go#219]
Greetings.
I am interested to help with arranging a separate CI pipeline, for an alternative compiler:
https://go.googlesource.com/gollvm/
. Currently x86_64, Aarch64 arch. are supported.

**Comment by janosdebugs** [comment]
Hey @advancedwebdeveloper we are in the process of reviewing old issues. If you can make gollvm work and send us a PR we would be interested in reviewing it. Unfortunately, we do not have capacity for developing such a switch ourselves.

**Comment by janosdebugs** [comment]
Hey @advancedwebdeveloper we are closing this issue for now, please feel free to reopen.
