### ISSUE TITLE
proper documentation!

### ISSUE THREAD

**Issue by Shashwatsh** [oVirt/ovirt-engine-sdk-go#82]
i notice that this SDK is not properly documented, it has examples but still all methods and types should be listed/documented on either readthedocs.io or godoc.

**Comment by imjoey** [comment]
@Shashwatsh  Exactly. I will complement the docs ASAP.

**Comment by sandrobonazzola** [comment]
Any progress?

**Comment by imjoey** [comment]
@sandrobonazzola As for now, the relevant docs is available at https://godoc.org/github.com/oVirt/go-ovirt , which is auto-generated by the project of `oVirt/ovirt-engine-api-model`. While to be honest, it's still a long way from well-documented. I'll make this done within this week. Thanks.

**Comment by janosdebugs** [comment]
Hey folks, following up on this very old issue. It seems to me that we won't have the capacity to manually write more docs than we have for this library, and everything that could be done automatically has already been done.

We are in the process of developing an [overlay library](https://github.com/ovirt/go-ovirt-client) that simplifies many of the tasks with the oVirt Engine. It uses this library as a backend and has inline documentation that can be easily explored using an IDE or on [godoc.org](https://pkg.go.dev/github.com/ovirt/go-ovirt-client). That being said, it is very early in development and many API calls are still missing. If you wish to use it please open issues so we can implement them as needed.

**Comment by mwperina** [comment]
Hmm, is there any way how to improve Go SDK documentation similarly to other SDKs?

Python: http://ovirt.github.io/ovirt-engine-sdk/4.4/
Java: https://javadoc.io/doc/org.ovirt.engine.api/sdk/latest/index.html
Ruby: https://www.rubydoc.info/gems/ovirt-engine-sdk/

**Comment by janosdebugs** [comment]
After talking to @mwperina I added a small amount of auto-generated documentation similar to Python, etc.

**Comment by mwperina** [comment]
Thanks Janos!
